### PR TITLE
Wheels1

### PR DESCRIPTION
**Pull request by darcymason**

### CODE REVIEW

**Comment by darcymason** [comment]
Trying out `scikit-build-core`; from my reading `scikit-build` was often recommended, now they are moving to `scikit-build-core`, but is still somewhat early it sounds like.

I can build a linux wheel with `python -m build` locally in WSL, which when installed does have a number of .so[.X] libs, which PyTurboJPEG was able to load and use if I pointed directly to the .so.0 file (I used that one because if was the same name as the one installed globally when I built libjpeg-turbo directly).

Not having so much luck with `cibuildwheel` so far, locally with `cibuidwheel --platform linux` it says it built the wheel, then tries to pass on the location to `auditwheel`, which throws an error about not finding the wheel.

**Comment by darcymason** [comment]
Hmm... the Windows builds work, may be simply because (AFAICT) it doesn't do the `auditwheel` step.  That step is supposed to (from my reading) link in any other dependencies needed by the library into the wheel, but I don't think there are any; perhaps the auditwheel step can also be skipped in linux/mac.

**Comment by darcymason** [comment]
In the workflow here, `auditwheel` is running, but complaining about missing system libraries for linux/mac.

Debugging... learning this as I go, no expert in cmake, building extensions, etc.

Using `auditwheel -vv show <wheel file>` locally, it reports:
```
The wheel references external versioned symbols in these
system-provided shared libraries: libjpeg.so.62 with versions
{'LIBJPEGTURBO_6.2', 'LIBJPEG_6.2'}, libc.so.6 with versions
{'GLIBC_2.7', 'GLIBC_2.14', 'GLIBC_2.11', 'GLIBC_2.3.4', 'GLIBC_2.4',
'GLIBC_2.2.5', 'GLIBC_2.3', 'GLIBC_2.34'}, libm.so.6 with versions
{'GLIBC_2.2.5'}, libturbojpeg.so.0 with versions {'TURBOJPEG_3'}

This constrains the platform tag to "manylinux_2_34_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.

In order to achieve the tag platform tag "manylinux_2_35_x86_64" the
following shared library dependencies will need to be eliminated:

libjpeg.so.62, libturbojpeg.so.0
```

Both of these `.so`s (and many others) are actually in the wheel (using `python -m zipfile --list <wheel file>`); they are in a "lib64" subdirectory.  So somehow it is not finding them.  I keep seeing things about `cmake` `rpath`s when searching for similar issues online ... but I haven't learned enough to figure out if that is the way out.

Or, perhaps there is a way to constrain to the platform tag suggested?

However, as per my earlier comment in this PR, I was able to load the local wheel and use it with PyTurboJPEG, loading the `.so.0` directly.   I assume the `libjpeg.so.62` is purely for compatibility with original libjpeg, so is not used (PyTurboJPEG uses the libjpeg-turbo API).  Alternatively, maybe ctypes loading looks for linked libraries in the same folder as the one being loaded?  Could perhaps just config away the `auditwheel` step and see what happens.  Setting this aside until tomorrow, but any insights welcome.

**Comment by mrbean-bremen** [comment]
Sorry for ignoring this... the problem is that I have no real knowledge in this area, and to help I would have to do some research myself. Unfortunately, my brain doesn't agree with the current weather, and after my day job I'm not really able to think coherently. Even the weekends are not much help... I should probably move to Scandinavia... or to Canada 😀

**Comment by darcymason** [comment]
> Sorry for ignoring this... the problem is that I have no real knowledge in this area, and to help I would have to do some research myself.

Oh, that's no problem.  I think I may have found some 'models' for how to do it, in particular someone doing something pretty similar [here](https://github.com/spglib/spglib/blob/94d288f81471dbb57a12395f1e907f687e487efe/python/CMakeLists.txt), pointed to by a discussion in issue 374 on scikit-build-core.


> Unfortunately, my brain doesn't agree with the current weather, and after my day job I'm not really able to think coherently. Even the weekends are not much help... I should probably move to Scandinavia... or to Canada 😀

lol, I understand.  But Canada has had its share of terrible weather too, forest fires, floods etc. in the last few years.  Thankfully, my region has been spared so far except for a few very smokey days this year.

**Comment by darcymason** [comment]
On debugging, the submodule libjpeg-turbo was never actually fetched.  Tried recreating submodules, etc., with no effect.  Started over in new repo, renamed this one to "old-pylibjpeg-turbo", and have working workflows now.  Will likely delete this "old" repo before long.

**Pull request merged**
